adminUser:
  password: local:jx/adminUser:password
  username: ram4444
docker:
  email: dionysbiz@gmail.com
  password: local:jx/docker:password
  url: https://index.docker.io/v1/
  username: dionysbiz
enableDocker: true
pipelineUser:
  email: dionysbiz@gmail.com
  token: local:jx/pipelineUser:token
  username: dionysbot
prow:
  hmacToken: local:jx/prow:hmacToken
